# Content Areas {-}

Source: <a href="https://www.ascp.org/content/board-of-certification/get-credentialed#" target="_blank">MLT(ASCP) and MLS(ASCP) Certifications > Applicant Resources > Content Guideline</a>

Major content areas covered:

## **Principles of Immunology** {-}

*   [Immune System Physiology](immune-system-physiology.html)
*   [Immunoglobulins](immunoglobulins.html)
*   [Antigen-Antibody Interactions](ag-ab-interactions.html)
*   [Complement](complement.html)

## **Diseases of the Immune System** {-}

*   [Autoimmunity](autoimmunity.html)
*   [Hypersensitivity](hypersensitivity.html)
*   [Immunoproliferative Diseases](immunoproliferative-diseases.html)
*   [Immunodeficiency](immunodeficiency.html)

## **Transplantation** {-}

*   [Graft-versus-host Disease](graft-versus-host-disease.html)
*   [HLA Typing](hla-typing.html)
*   [Tumor Immunology](tumor-immunology.html)

## **Infectious Disease Serology** {-}

*   [Clinical Significance and Epidemiology of Viral Pathogens](viral-pathogens.html)
*   [Stages of Infection of Treponema pallidum and Borrelia burgdorferi](t.-pallidum-b.-burgdorferi.html)
*   [Tuberculosis Infection](tuberculosis.html)

## **Serologic Procedures** {-}

*   [ANA](ana.html
*   [Thyroid Antibodies](thyroid-antibodies.html)
*   [Rheumatoid Factor](rheumatoid-factor.html)
*   [Labeled Immunoassays](labeled-immunoassays.html)
*   [Nontreponemal Syphilis Testing](nontreponemal-syphilis.html)
*   [Treponemal Syphilis Testing](treponemal-syphilis.html)
*   [Cytokine Testing](cytokine.html)
*   [Immunofluorescence](immunofluorescence.html)

## **Test Results** {-}

*   [Interpretation](interpretation.html)
*   [Confirmatory Testing](confirmatory-testing.html)
*   [Disease State Correlation](disease-correlation.html)

## Last Updated {-}

Last edit pushed to this site was on <span id="last_updated">`r Sys.Date()`</span>

